const substages = {
  metaData: [
    { name: "id", datatype: "numb" },
    { name: "assistance", datatype: "text" },
    { name: "mao_edition_id", datatype: "numb" },
    { name: "is_initial", datatype: "bool" },
    { name: "color", datatype: "text" },
    { name: "substages", datatype: "json" },
    { name: "substage_exist", datatype: "bool" },
    { name: "route_exist", datatype: "bool" },
    { name: "r_n_", datatype: "numb" },
  ],
  data: [
    {
      id: 1,
      assistance: "Педезребае ба Збе",
      mao_edition_id: 1,
      is_initial: true,
      color: "#E39C7D",
      substages: null,
      substage_exist: true,
      route_exist: true,
      r_n_: 1,
    },
    {
      id: 2,
      assistance: "Даагбесзака",
      mao_edition_id: 1,
      is_initial: false,
      color: "#DB97C8",
      substages: null,
      substage_exist: true,
      route_exist: true,
      r_n_: 2,
    },
    {
      id: 3,
      assistance: "Лечебае",
      mao_edition_id: 1,
      is_initial: false,
      color: "#6EC5C6",
      substages: null,
      substage_exist: true,
      route_exist: true,
      r_n_: 3,
    },
    {
      id: 4,
      assistance: "Даспабсербее баблюдебае",
      mao_edition_id: 1,
      is_initial: false,
      color: "#70A9EB",
      substages: null,
      substage_exist: true,
      route_exist: true,
      r_n_: 4,
    },
    {
      id: 5,
      assistance: "Реабалазацая",
      mao_edition_id: 1,
      is_initial: false,
      color: "#e197a0",
      substages: null,
      substage_exist: true,
      route_exist: true,
      r_n_: 5,
    },
    {
      id: 6,
      assistance: "Паллаазавбая педещь",
      mao_edition_id: 1,
      is_initial: false,
      color: "#6b73d5",
      substages: null,
      substage_exist: true,
      route_exist: true,
      r_n_: 6,
    },
  ],
};
